<img id="image-main"
     src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
     alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
     title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>"  width="150px"/>
<div class="product-shop">
    <div class="product-name">
        <span class="h1"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
    </div>
    <br/>
    <div class="price-info">
        <?php echo $this->getPriceHtml($_product); ?>
        <?php echo $this->getChildHtml('bundle_prices') ?>
        <?php echo $this->getTierPriceHtml() ?>
    </div>

    <?php echo $this->getChildHtml('alert_urls') ?>

    <?php if ($_product->getShortDescription()):?>
        <div class="short-description">
            <div class="std">
                <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
            </div>
        </div>
    <?php endif;?>

    <?php echo $this->getChildHtml('other');?>
</div>
<div class="add-to-cart-buttons">
    <div class="button-green">
        <button type="button"
                title="<?php echo $buttonTitle ?>"
                class="button button-green"
                onclick="productAddToCartForm.submit(this)">
            <span>
                <span>
                    <?php echo $buttonTitle ?>
                </span>
            </span>
        </button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
</div>
