<?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>

<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="input-box">
        <a title="" rel="nofollow"><div class="button search-button open-input" id="button-s"></div></a>
       <div id="search-div" class="search-div">
        <input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>"
               value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry"
               maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>"
               placeholder="<?php echo $this->quoteEscape($this->__('')) ?>" />
           <button type="submit" title="<?php echo $this->quoteEscape($this->__('Search')) ?>"
                   class="button search-button"><span><span><?php echo $this->__('Search') ?></span></span></button>
       </div>
       </div>
    <script type="text/javascript">
        //<![CDATA[
        var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
        searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
    </script>
</form>

<script>
    var modalInput = document.getElementById('search-div');
    var buttonOpen = document.getElementById("button-s");
    var inputField = document.getElementById("search");

    buttonOpen.onclick = function () {
        modalInput.style.display = "block";
        buttonOpen.style.display = "none";
    };

    document.addEventListener('click', function (event) {
        if (event.target != buttonOpen && event.target != inputField) {
            modalInput.style.display = "none";
            buttonOpen.style.display = "block";
        }
    });

</script>
